# Generated by Django 5.0 on 2024-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth', '0011_alter_user_verify_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verify_code',
            field=models.CharField(default='088082', max_length=6, verbose_name='Код вeрификации'),
        ),
    ]
